import BootstrapImport from "./imports/BootstrapImport";
import 'bootstrap/dist/css/bootstrap.min.css';
import "./globals.css";
import './scss/index.scss';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        {children}

        <BootstrapImport />
      </body>
    </html>
  );
}
